package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
*/

public interface HelloOperations 
{
  String sayHello ();

  // This Line is an operation statement.
  void shutdown ();
} // interface HelloOperations
